require('dotenv').config();
const PressRelease = require('./src/models/PressRelease');

// Function to transform the provided data to PressRelease model format
function transformPressReleaseData(item) {
  // Extract boolean flags from one_field_for array
  const flags = item.one_field_for || [];
  const best_seller = flags.includes('best seller');
  const newly_added = flags.includes('newly added');
  const exclusive = flags.includes('exclusive');
  const best_price_guarantee = flags.includes('best price guarantee');
  const vaas_choice = flags.includes('VaaS Choice');

  // Handle Google optimization fields
  let google_search_optimised_publications = null;
  if (item.Google_Search_Optimised === 'Guaranteed') {
    // For guaranteed, we need a number - let's use a default or calculate based on distribution
    google_search_optimised_publications = Math.floor(item.Distribution_to_No_of_Media_Websites / 10);
  }

  let google_news_index_publications = null;
  if (item.Google_News_Index === 'Guaranteed') {
    google_news_index_publications = Math.floor(item.Guaranteed_No_of_Media_Placements / 2);
  }

  // Handle word_limit - convert to integer, take first number if range
  let word_limit = item.Word_Limit;
  if (typeof word_limit === 'string') {
    // Extract first number from range like "400-1200"
    const match = word_limit.match(/\d+/);
    word_limit = match ? parseInt(match[0], 10) : 600; // default to 600 if no number found
  } else if (typeof word_limit === 'number') {
    word_limit = word_limit;
  } else {
    word_limit = 600; // default
  }

  return {
    name: item.Press_Release_Name,
    region: Array.isArray(item.Region) ? item.Region[0] : item.Region, // Take first region
    niche: Array.isArray(item.Niche) ? item.Niche[0] : item.Niche, // Take first niche
    distribution_media_websites: item.Distribution_to_No_of_Media_Websites,
    guaranteed_media_placements: item.Guaranteed_No_of_Media_Placements,
    end_client_media_details: item.End_Client_Media_Details_in_Press_Release,
    middlemen_contact_details: item.Middlemen_or_PR_Agency_Contact_Details_in_Press_Release,
    google_search_optimised_status: item.Google_Search_Optimised,
    google_search_optimised_publications: google_search_optimised_publications,
    google_news_index_status: item.Google_News_Index,
    google_news_index_publications: google_news_index_publications,
    images_allowed: item.No_of_Images_allowed,
    word_limit: word_limit,
    package_options: item.Press_Release_Package_Options,
    price: item.Price,
    turnaround_time: item.Turnaround_time_in_days.toString(),
    customer_info_needed: Array.isArray(item.Information_and_Documents_needed_from_customers)
      ? item.Information_and_Documents_needed_from_customers.join(', ')
      : item.Information_and_Documents_needed_from_customers,
    description: item.One_area_for_description,
    image_logo: item.One_image_or_logo_section,
    best_seller: best_seller,
    newly_added: newly_added,
    exclusive: exclusive,
    best_price_guarantee: best_price_guarantee,
    vaas_choice: vaas_choice,
    content_writing_assistance: item.Content_writing_assistance.includes('Required'),
    submitted_by_admin: 1, // Assuming admin submission
    is_active: true
  };
}

// Press release data from the provided array (first 10 items for testing)
const PRESS_RELEASE_DATA =  
[
  {
    "Press_Release_Name": "Headline (Max 200 characters)",
    "Region": ["Asia", "Middle East", "North America", "USA", "GCC", "India", "Russia", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3", "Sports", "Entertainment", "Gambling", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 5000,
    "Guaranteed_No_of_Media_Placements": 200,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Mandatory",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": "400-1200",
    "Press_Release_Package_Options": ["Diamond", "Titanium", "Platinum", "Gold", "Silver", "Bronze"],
    "Price": 5000,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller", "newly added", "VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title / Headline",
    "Region": ["North America", "USA", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 450,
    "Guaranteed_No_of_Media_Placements": 150,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 349,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "News Headline",
    "Region": ["Global", "GCC", "India", "China", "Russia"],
    "Niche": ["Cyber", "Web3", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Not Allowed",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 4,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 2200,
    "Turnaround_time_in_days": 3,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline (100 characters max)",
    "Region": ["Global", "Asia", "North America", "GCC", "India", "China", "Russia"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3", "Sports", "Entertainment", "Gambling", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 5800,
    "Guaranteed_No_of_Media_Placements": 250,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Mandatory",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 6,
    "Word_Limit": "500-1200",
    "Press_Release_Package_Options": ["Diamond", "Titanium", "Platinum", "Gold", "Silver"],
    "Price": 4750,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller", "VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Title of Press Release",
    "Region": ["Global", "Asia", "North America", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3", "Sports", "Entertainment", "Gambling", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 3500,
    "Guaranteed_No_of_Media_Placements": 150,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 500,
    "Press_Release_Package_Options": ["Pro+", "Pro", "Basic"],
    "Price": 299,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["North America", "USA", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Sports", "Entertainment", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 1200,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold", "Silver"],
    "Price": 1499,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline (Max 250 characters)",
    "Region": ["Global", "Asia", "North America", "GCC", "India", "China", "Russia"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3", "Sports", "Entertainment", "Gambling", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 9000,
    "Guaranteed_No_of_Media_Placements": 300,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Mandatory",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 8,
    "Word_Limit": "400-1200",
    "Press_Release_Package_Options": ["Diamond", "Titanium", "Platinum", "Gold", "Silver", "Bronze"],
    "Price": 7500,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller", "exclusive", "VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Headline",
    "Region": ["Global", "GCC", "India", "China", "Russia"],
    "Niche": ["Cyber", "Web3", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 250,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Not Allowed",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 699,
    "Turnaround_time_in_days": 3,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "News Headline",
    "Region": ["Global", "GCC", "India", "China"],
    "Niche": ["Cyber", "Web3", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 120,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Not Allowed",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum"],
    "Price": 1199,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance", "Sports", "Entertainment", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 400,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 199,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Story Headline",
    "Region": ["Global", "North America", "GCC", "India", "China"],
    "Niche": ["Gaming", "Sports", "Entertainment", "Web3"],
    "Distribution_to_No_of_Media_Websites": 250,
    "Guaranteed_No_of_Media_Placements": 80,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Not Allowed",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 4,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum"],
    "Price": 899,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Headline",
    "Region": ["Global", "Asia", "North America", "GCC", "India", "China", "Russia"],
    "Niche": ["Cyber", "Web3", "Finance"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Not Allowed",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 549,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["Global", "North America", "GCC", "India", "China"],
    "Niche": ["Finance", "Business", "Web3"],
    "Distribution_to_No_of_Media_Websites": 400,
    "Guaranteed_No_of_Media_Placements": 120,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 1299,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline (Max 150 characters)",
    "Region": ["Global", "North America", "Asia"],
    "Niche": ["General", "Business", "Finance", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 1000,
    "Guaranteed_No_of_Media_Placements": 150,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Mandatory",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 500,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 1099,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Release Headline",
    "Region": ["UK", "Europe", "Middle-East", "GCC"],
    "Niche": ["General", "Business", "Sports", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 600,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 4,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 800,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 450,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 179,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["Europe", "Russia", "GCC"],
    "Niche": ["General", "Business", "Finance", "Cyber"],
    "Distribution_to_No_of_Media_Websites": 350,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 490,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Title / Headline",
    "Region": ["Middle-East", "GCC", "North Africa"],
    "Niche": ["General", "Business", "Finance", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 250,
    "Guaranteed_No_of_Media_Placements": 80,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 399,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Headline",
    "Region": ["Global", "North America", "Asia", "GCC", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Sports", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 500,
    "Guaranteed_No_of_Media_Placements": 150,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 299,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["UK", "Europe", "North America"],
    "Niche": ["General", "Business", "Finance"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 430,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Headline",
    "Region": ["Global", "North America", "GCC", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 400,
    "Guaranteed_No_of_Media_Placements": 120,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 4,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 249,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Title",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 149,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["Global", "North America", "Asia", "GCC", "India"],
    "Niche": ["General", "Business", "Entertainment", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 350,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 500,
    "Press_Release_Package_Options": ["Pro+", "Pro", "Free"],
    "Price": 99,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance", "Cyber"],
    "Distribution_to_No_of_Media_Websites": 400,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 179,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline (Max 256 characters)",
    "Region": ["Global", "Asia", "North America", "GCC", "India", "China", "Russia"],
    "Niche": ["General", "Business", "Finance", "Legal"],
    "Distribution_to_No_of_Media_Websites": 11000,
    "Guaranteed_No_of_Media_Placements": 350,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Mandatory",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 8,
    "Word_Limit": "500-1200",
    "Press_Release_Package_Options": ["Diamond", "Titanium", "Platinum"],
    "Price": 8000,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "News Headline",
    "Region": ["Asia", "China", "Japan", "SEA"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 600,
    "Guaranteed_No_of_Media_Placements": 150,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 1199,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["Asia-Pacific", "China", "Japan", "Korea"],
    "Niche": ["General", "Business", "Finance", "Tech"],
    "Distribution_to_No_of_Media_Websites": 500,
    "Guaranteed_No_of_Media_Placements": 130,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 4,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 799,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["Asia", "SEA", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 400,
    "Guaranteed_No_of_Media_Placements": 120,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 999,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline (Max 200 characters)",
    "Region": ["India", "South-Asia"],
    "Niche": ["General", "Business", "Finance", "Sports", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 350,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 180,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Headline",
    "Region": ["Global", "North America", "GCC", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 149,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["SE-Asia", "Singapore", "Thailand", "Vietnam"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 350,
    "Guaranteed_No_of_Media_Placements": 110,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 899,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "News Title / Headline",
    "Region": ["Asia", "China", "India", "Japan", "Korea"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 500,
    "Guaranteed_No_of_Media_Placements": 130,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 4,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 1099,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["Japan", "North-Asia"],
    "Niche": ["General", "Business", "Tech", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 250,
    "Guaranteed_No_of_Media_Placements": 80,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 500,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 290,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Headline",
    "Region": ["Europe", "Russia", "GCC"],
    "Niche": ["General", "Business", "Finance", "Cyber"],
    "Distribution_to_No_of_Media_Websites": 400,
    "Guaranteed_No_of_Media_Placements": 120,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 540,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["Global", "North America", "Asia", "GCC", "India"],
    "Niche": ["General", "Business", "Finance", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 450,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 799,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 129,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Title",
    "Region": ["India", "South-Asia"],
    "Niche": ["General", "Business", "Finance", "Sports", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 250,
    "Guaranteed_No_of_Media_Placements": 90,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 145,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["GCC", "MENA"],
    "Niche": ["General", "Business", "Finance", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 449,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["South-Africa", "Kenya", "Nigeria", "Egypt"],
    "Niche": ["General", "Business", "Finance", "Sports"],
    "Distribution_to_No_of_Media_Websites": 200,
    "Guaranteed_No_of_Media_Placements": 70,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 500,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 190,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "News Headline",
    "Region": ["Global", "North America", "GCC", "India", "China"],
    "Niche": ["Cyber", "Web3", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 250,
    "Guaranteed_No_of_Media_Placements": 90,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Not Allowed",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 649,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["North America", "USA"],
    "Niche": ["General", "Business", "Finance"],
    "Distribution_to_No_of_Media_Websites": 150,
    "Guaranteed_No_of_Media_Placements": 50,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Not Guaranteed",
    "Google_News_Index": "Not Guaranteed",
    "No_of_Images_allowed": 2,
    "Word_Limit": 500,
    "Press_Release_Package_Options": ["Silver", "Bronze"],
    "Price": 79,
    "Turnaround_time_in_days": 3,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["North America", "USA"],
    "Niche": ["Legal", "Business"],
    "Distribution_to_No_of_Media_Websites": 200,
    "Guaranteed_No_of_Media_Placements": 75,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Not Allowed",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 349,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Title / Headline",
    "Region": ["MENA", "GCC"],
    "Niche": ["General", "Business", "Finance"],
    "Distribution_to_No_of_Media_Websites": 150,
    "Guaranteed_No_of_Media_Placements": 60,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 2,
    "Word_Limit": 500,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 399,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title / Headline",
    "Region": ["North America", "USA", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 450,
    "Guaranteed_No_of_Media_Placements": 150,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 349,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["North America", "USA", "India", "China"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Sports", "Entertainment", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 1200,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold", "Silver"],
    "Price": 1499,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance", "Cyber"],
    "Distribution_to_No_of_Media_Websites": 400,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 179,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["North America", "USA"],
    "Niche": ["General", "Business", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 250,
    "Guaranteed_No_of_Media_Placements": 90,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold"],
    "Price": 119,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 450,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 179,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["North America", "USA", "India"],
    "Niche": ["General", "Business", "Finance"],
    "Distribution_to_No_of_Media_Websites": 300,
    "Guaranteed_No_of_Media_Placements": 100,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 99,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline (RU/EN)",
    "Region": ["Russia", "CIS"],
    "Niche": ["General", "Business", "Finance"],
    "Distribution_to_No_of_Media_Websites": 200,
    "Guaranteed_No_of_Media_Placements": 80,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 270,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Headline",
    "Region": ["UK", "Europe", "North America"],
    "Niche": ["General", "Business", "Finance", "Tech"],
    "Distribution_to_No_of_Media_Websites": 350,
    "Guaranteed_No_of_Media_Placements": 110,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 4,
    "Word_Limit": 700,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 749,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline",
    "Region": ["SE-Asia", "Singapore", "Malaysia", "Thailand"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 600,
    "Guaranteed_No_of_Media_Placements": 150,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 5,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 1099,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["VaaS Choice"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Title",
    "Region": ["North America", "USA"],
    "Niche": ["General", "Business", "Gaming"],
    "Distribution_to_No_of_Media_Websites": 200,
    "Guaranteed_No_of_Media_Placements": 85,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Gold", "Silver"],
    "Price": 179,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["newly added"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Headline (Max 300 characters)",
    "Region": ["Global", "North America", "Europe", "Asia"],
    "Niche": ["General", "Business", "Finance", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 10000,
    "Guaranteed_No_of_Media_Placements": 300,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Mandatory",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 8,
    "Word_Limit": "400-1200",
    "Press_Release_Package_Options": ["Diamond", "Titanium", "Platinum"],
    "Price": 6999,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["exclusive"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "News Release Headline",
    "Region": ["Global", "North America", "Asia", "GCC"],
    "Niche": ["General", "Business", "Finance", "Cyber", "Web3"],
    "Distribution_to_No_of_Media_Websites": 5000,
    "Guaranteed_No_of_Media_Placements": 200,
    "End_Client_Media_Details_in_Press_Release": "Mandatory",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 6,
    "Word_Limit": "500-1200",
    "Press_Release_Package_Options": ["Diamond", "Platinum", "Gold"],
    "Price": 3499,
    "Turnaround_time_in_days": 1,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best seller"],
    "Content_writing_assistance": ["Required", "Not required"]
  },
  {
    "Press_Release_Name": "Press Release Title",
    "Region": ["North America", "USA", "UK"],
    "Niche": ["General", "Business", "Finance", "Entertainment"],
    "Distribution_to_No_of_Media_Websites": 500,
    "Guaranteed_No_of_Media_Placements": 125,
    "End_Client_Media_Details_in_Press_Release": "Optional",
    "Middlemen_or_PR_Agency_Contact_Details_in_Press_Release": "Optional",
    "Google_Search_Optimised": "Guaranteed",
    "Google_News_Index": "Guaranteed",
    "No_of_Images_allowed": 3,
    "Word_Limit": 600,
    "Press_Release_Package_Options": ["Platinum", "Gold", "Silver"],
    "Price": 199,
    "Turnaround_time_in_days": 2,
    "Information_and_Documents_needed_from_customers": ["Authorised person name", "Email", "Phone number", "Website", "Press release on letter head", "letter of authorisation , if release is via agency not via direct client", "Company registraion document"],
    "One_area_for_description": "1 textarea",
    "One_image_or_logo_section": "1 logo upload",
    "one_field_for": ["best price guarantee"],
    "Content_writing_assistance": ["Required", "Not required"]
  }
];

class PressReleasePopulator {
  async populatePressReleases() {
    try {
      console.log('Starting press release population...');

      let successCount = 0;
      let errorCount = 0;

      for (const item of PRESS_RELEASE_DATA) {
        try {
          // Transform the data to match PressRelease model
          const pressReleaseData = transformPressReleaseData(item);

          await this.savePressRelease(pressReleaseData);
          successCount++;
          console.log(`Saved press release: ${pressReleaseData.name}`);
        } catch (error) {
          console.error(`Error processing press release "${item.Press_Release_Name}":`, error.message);
          errorCount++;
        }
      }

      console.log(`Press release population complete. Success: ${successCount}, Errors: ${errorCount}`);

    } catch (error) {
      console.error('Error in populatePressReleases:', error);
    }
  }

  async savePressRelease(pressReleaseData) {
    // Check if press release already exists
    const existing = await this.findPressReleaseByName(pressReleaseData.name);
    if (existing) {
      console.log(`Press release ${pressReleaseData.name} already exists, skipping...`);
      return;
    }

    await PressRelease.create(pressReleaseData);
  }

  async findPressReleaseByName(name) {
    try {
      const sql = 'SELECT * FROM press_releases WHERE name = $1';
      const result = await require('./src/config/database').query(sql, [name]);
      return result.rows[0] || null;
    } catch (error) {
      console.error('Error checking existing press release:', error);
      return null;
    }
  }
}

// Run the populator
if (require.main === module) {
  const populator = new PressReleasePopulator();
  populator.populatePressReleases()
    .then(() => {
      console.log('Press release population script completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Press release population script failed:', error);
      process.exit(1);
    });
}

module.exports = PressReleasePopulator;