require('dotenv').config();
const db = require('./src/config/database');
const Publication = require('./src/models/Publication');
const Group = require('./src/models/Group');

const PUBLICATIONS_DATA = [
    { sn: 1, region: 'UAE', publication_name: 'WOW RAK', publication_url: 'https://wow-rak.com/', language: 'English', publication_primary_focus: 'General', practical_tat: '5', price_usd: '500', instagram: 'https://www.instagram.com/wow.rak/', facebook: 'https://www.facebook.com/rakiswow', linkedin: 'https://www.linkedin.com/company/wow-rak', image: 'https://wow-rak.com/wp-content/uploads/2025/04/wow-media-logo-11-e1745530363765.png.webp', twitter: '', da: 24, dr: null },
    { sn: 2, region: 'UAE', publication_name: 'Nukta', publication_url: 'https://nukta.com/', language: 'English', publication_primary_focus: 'General', practical_tat: '5', price_usd: '900', instagram: 'https://www.instagram.com/nuktadotcom', facebook: 'https://www.facebook.com/nuktadotcom', linkedin: 'https://www.linkedin.com/company/nuktadotcom', image: 'https://nukta.com/media-library/logo.png?id=61012683', twitter: 'https://twitter.com/nuktadotcom', da: 27, dr: null },
    { sn: 3, region: 'UAE', publication_name: 'Al Ethiad English', publication_url: 'https://en.aletihad.ae/', language: 'English / Arabic', publication_primary_focus: 'Newpaper', practical_tat: '15', price_usd: '4,000', instagram: '', facebook: '', linkedin: '', image: 'https://static.alittihad.ae/front/Content/AlittihadEnglish/img/logo.svg', twitter: '', da: 51, dr: null },
    { sn: 4, region: 'UAE', publication_name: 'Emirates 247', publication_url: 'https://www.emirates247.com/', language: 'English', publication_primary_focus: 'Newpaper', practical_tat: '15', price_usd: '3,500', instagram: 'https://www.instagram.com/emirates247/', facebook: 'https://www.facebook.com/Emirates247', linkedin: 'https://www.linkedin.com/company/emirates-24-7', image: 'https://www.emirates247.com/res/img/livebtn.png', twitter: 'https://twitter.com/Emirates247', da: 86, dr: 80 },
    { sn: 5, region: 'UAE', publication_name: 'The National', publication_url: 'https://www.thenationalnews.com/uae/', language: 'English', publication_primary_focus: 'Newpaper', practical_tat: '15', price_usd: '9,500', instagram: 'https://www.instagram.com/thenationalnewscom', facebook: 'https://www.facebook.com/thenationalnews', linkedin: 'https://www.linkedin.com/company/the-national-news', image: 'https://www.thenationalnews.com/pf/resources/images/logo.webp?d=1091', twitter: 'https://twitter.com/TheNationalNews', da: 90, dr: 89 },
    { sn: 6, region: 'UAE', publication_name: 'Gulf Today', publication_url: 'https://www.gulftoday.ae/', language: 'English', publication_primary_focus: 'Newpaper', practical_tat: '5', price_usd: '700', instagram: '', facebook: '', linkedin: '', image: '', twitter: '', da: null, dr: null },
    { sn: 7, region: 'UAE', publication_name: 'UAE Barq', publication_url: 'https://www.uaebarq.ae/en/', language: 'English', publication_primary_focus: 'News', practical_tat: '5', price_usd: '500', instagram: 'https://www.instagram.com/uae_barq_en/', facebook: 'https://www.facebook.com/uaebarq', linkedin: 'https://www.linkedin.com/in/uaebarqgroup/', image: 'https://www.uaebarq.ae/en/wp-content/uploads/2026/01/Capture-3-310x165.png', twitter: 'https://twitter.com/uae_barq_en', da: null, dr: null },
    { sn: 8, region: 'UAE', publication_name: 'Al Bayan', publication_url: 'https://www.albayan.ae/', language: 'Arabic', publication_primary_focus: 'Newpaper', practical_tat: '10', price_usd: '4,000', instagram: 'https://www.instagram.com/albayan_ae/', facebook: 'https://www.facebook.com/albayan.ae', linkedin: 'https://ae.linkedin.com/company/albayan-ae', image: 'https://www.albayan.ae/assets/images/logo.svg', twitter: 'https://twitter.com/albayan_ae', da: 91, dr: 85 },
    { sn: 9, region: 'UAE', publication_name: 'Emarat Al Youm', publication_url: 'https://www.emaratalyoum.com/', language: 'Arabic', publication_primary_focus: 'Newpaper', practical_tat: '10', price_usd: '4,000', instagram: 'https://www.instagram.com/emaratalyoum', facebook: 'https://www.facebook.com/emaratalyoum', linkedin: 'https://www.linkedin.com/company/emarat-al-youm', image: 'https://www.emaratalyoum.com/polopoly_fs/1.1000000.1500000000!/image/logo.png', twitter: 'https://twitter.com/emaratalyoum', da: 83, dr: 78 },
    { sn: 10, region: 'UAE', publication_name: 'Al Khaleej', publication_url: 'https://www.alkhaleej.ae/', language: 'Arabic', publication_primary_focus: 'Newpaper', practical_tat: '5', price_usd: '1,500', instagram: 'https://www.instagram.com/alkhaleej.ae/', facebook: 'https://www.facebook.com/alkhaleej.ae/', linkedin: 'https://www.linkedin.com/company/alkhaleej-newspaper', image: 'https://www.alkhaleej.ae/themes/custom/alkhaleej/logo-print.png', twitter: 'https://twitter.com/alkhaleej', da: 82, dr: 78 },
    { sn: 11, region: 'Saudi', publication_name: 'Al Riyadh Daily', publication_url: 'https://www.alriyadhdaily.com/', language: 'English', publication_primary_focus: 'Newpaper', practical_tat: '5', price_usd: '1,500', instagram: 'https://www.instagram.com/alriyadhdaily', facebook: 'https://www.facebook.com/AlRiyadhDaily', linkedin: '', image: 'https://www.alriyadhdaily.com/img/logo.png', twitter: 'https://twitter.com/alriyadhdaily', da: null, dr: null },
    { sn: 12, region: 'Saudi', publication_name: 'Saudi Gazette', publication_url: 'https://saudigazette.com.sa/', language: 'English', publication_primary_focus: 'Newpaper', practical_tat: '10', price_usd: '3,000', instagram: '', facebook: '', linkedin: '', image: 'https://saudigazette.com.sa/themes/saudigazette/images/no-image.png', twitter: 'https://twitter.com/Saudi_Gazette', da: null, dr: null },
    { sn: 13, region: 'Saudi', publication_name: 'Okaz', publication_url: 'https://www.okaz.com.sa/', language: 'Arabic', publication_primary_focus: 'Newpaper', practical_tat: '10', price_usd: '3,000', instagram: 'https://www.instagram.com/okaz_news', facebook: 'https://www.facebook.com/OkazS', linkedin: 'https://www.linkedin.com/company/okaz-organization-for-press-and-publication', image: 'https://www.okaz.com.sa/okaz/uploads/global_files/okaz-logo.svg', twitter: 'https://twitter.com/OKAZ_online', da: 74, dr: 76 },
    { sn: 14, region: 'Qatar', publication_name: 'Gulf Times', publication_url: 'https://www.gulf-times.com/', language: 'English', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '800', instagram: 'https://www.instagram.com/gulftimes/', facebook: 'https://www.facebook.com/GulfTimesQatar/', linkedin: 'https://www.linkedin.com/company/gulf-times/', image: 'https://www.gulf-times.com/gulftimes/uploads/images/2023/11/15/222216.png', twitter: 'https://twitter.com/gulftimes_qatar', da: 72, dr: 76 },
    { sn: 15, region: 'Qatar', publication_name: 'Al Roya', publication_url: 'http://alroeya.ae/', language: 'Arabic', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '1,500', instagram: '', facebook: '', linkedin: '', image: '', twitter: '', da: 5, dr: null },
    { sn: 16, region: 'Oman', publication_name: 'The Arabian Stories', publication_url: 'https://www.thearabianstories.com/', language: 'English', publication_primary_focus: 'General', practical_tat: '5', price_usd: '500', instagram: 'https://www.instagram.com/thearabianstories/', facebook: 'https://www.facebook.com/thearabianstories/', linkedin: 'https://www.linkedin.com/company/thearabianstories/', image: 'https://www.thearabianstories.com/wp-content/themes/thearabianstories-child/assets/images/tas-logo-sticky.png', twitter: 'https://twitter.com/arabianstories', da: 48, dr: 54 },
    { sn: 17, region: 'Oman', publication_name: 'Times of Oman', publication_url: 'https://timesofoman.com/', language: 'English', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/timesofoman', facebook: 'https://www.facebook.com/timesofoman', linkedin: 'https://www.linkedin.com/company/times-of-oman', image: 'https://rssfeeds.timesofoman.com/assets/img/top-icons/tmag.png', twitter: 'https://twitter.com/timesofoman', da: 72, dr: 76 },
    { sn: 18, region: 'Oman', publication_name: 'Muscat Daily', publication_url: 'https://www.muscatdaily.com/', language: 'English', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/muscatdaily/', facebook: 'https://www.facebook.com/muscatdailyonline', linkedin: '', image: 'https://www.muscatdaily.com/wp-content/uploads/2023/09/masthead_MD-logo.webp', twitter: 'https://twitter.com/muscat_daily', da: 45, dr: null },
    { sn: 19, region: 'Middle East', publication_name: 'Mid East Info', publication_url: 'https://mid-east.info/', language: 'English', publication_primary_focus: 'General', practical_tat: '5', price_usd: '600', instagram: 'https://instagram.com/mideast.info', facebook: 'https://www.facebook.com/mideast.i', linkedin: 'https://www.linkedin.com/company/me-i-mid-east-info', image: 'https://mid-east.info/wp-content/uploads/2016/09/mei-logo.jpg', twitter: 'https://twitter.com/MidEastinfo', da: 29, dr: null },
    { sn: 20, region: 'Middle East', publication_name: 'the Finance 360', publication_url: 'https://www.thefinance360.com/', language: 'English', publication_primary_focus: 'Business, Trade, Economy, Finance, General', practical_tat: '5', price_usd: '700', instagram: 'https://www.instagram.com/thefinance360/', facebook: 'https://www.facebook.com/TheFinance360', linkedin: 'https://www.linkedin.com/company/thefinance360/', image: 'https://www.thefinance360.com/wp-content/uploads/2023/11/Final-Logo-01.png', twitter: 'https://twitter.com/TheFinance360', da: 25, dr: 21 },
    { sn: 21, region: 'Middle East', publication_name: 'The Finance World', publication_url: 'https://thefinanceworld.com/', language: 'English', publication_primary_focus: 'Business, Trade, Economy, Finance, General', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/financeworldmagazine/', facebook: 'https://thefinanceworld.com/#', linkedin: 'https://www.linkedin.com/company/financeworldmagazine/', image: 'https://b2544466.smushcdn.com/2544466/wp-content/uploads/2023/12/FW-white-logo.png?lossy=1&strip=1&webp=1', twitter: 'https://twitter.com/financeworldmag', da: 28, dr: null },
    { sn: 22, region: 'Middle East', publication_name: 'About her', publication_url: 'https://www.abouther.com/', language: 'English', publication_primary_focus: 'Lifestyle', practical_tat: '10', price_usd: '3,000', instagram: 'https://www.instagram.com/aboutherksa/', facebook: 'https://www.facebook.com/AboutHerKSA', linkedin: 'https://www.linkedin.com/company/about-her-ksa', image: 'https://www.abouther.com/sites/default/files/pictures/26/420under30_banner.jpg', twitter: 'https://twitter.com/AboutHerKSA', da: 25, dr: 31 },
    { sn: 23, region: 'Middle East', publication_name: 'List Magazine', publication_url: 'https://www.listmag.com/en', language: 'English', publication_primary_focus: 'Lifestyle', practical_tat: '10', price_usd: '3,000', instagram: 'https://www.instagram.com/listmag.official', facebook: 'https://www.facebook.com/listmag.official', linkedin: 'https://www.linkedin.com/company/listmag-official', image: 'https://www.listmag.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.a3b72782.png&w=256&q=75', twitter: 'https://twitter.com/listmag_sa', da: 38, dr: 42 },
    { sn: 24, region: 'Middle East', publication_name: 'Ashraq Al Awsat English', publication_url: 'https://english.aawsat.com/', language: 'English', publication_primary_focus: 'Business, Trade, Economy, Finance, General', practical_tat: '10', price_usd: '4,000', instagram: '', facebook: '', linkedin: '', image: 'https://english.aawsat.com/themes/custom/enaawsatv3/img/subscribe.jpg', twitter: '', da: 68, dr: null },
    { sn: 25, region: 'Middle East', publication_name: 'Arab News', publication_url: 'https://www.arabnews.com/', language: 'English', publication_primary_focus: 'Business, Trade, Economy, Finance, General', practical_tat: '10', price_usd: '4,000', instagram: '', facebook: '', linkedin: '', image: 'https://www.arabnews.com/sites/all/themes/narabnews/assets/img/ads/job4.jpg', twitter: '', da: 62, dr: null },
    { sn: 26, region: 'Middle East', publication_name: 'Gulf Business', publication_url: 'https://gulfbusiness.com/', language: 'English', publication_primary_focus: 'Business, Trade, Economy, Finance, General', practical_tat: '10', price_usd: '5,000', instagram: 'https://instagram.com/gulfbusiness', facebook: 'https://facebook.com/GulfBusiness', linkedin: '', image: 'https://i1.wp.com/gulfbusiness.com/wp-content/uploads/2026/01/Sam-North-market-analyst-at-eToro.png?resize=300%2C244&ssl=1', twitter: 'https://twitter.com/GulfBusiness', da: 43, dr: null },
    { sn: 27, region: 'Middle East', publication_name: 'MENA FN', publication_url: 'https://menafn.com/', language: 'English', publication_primary_focus: 'General', practical_tat: '5', price_usd: '500', instagram: 'https://www.instagram.com/menafn/', facebook: 'https://www.facebook.com/MENAFN', linkedin: 'https://www.linkedin.com/company/menafn', image: 'https://menafn.com/images/shared/menafn_logo.png', twitter: 'https://twitter.com/MENAFN', da: 78, dr: 81 },
    { sn: 28, region: 'Middle East', publication_name: 'Al Bawaba', publication_url: 'https://www.albawaba.com/', language: 'English', publication_primary_focus: 'General', practical_tat: '5', price_usd: '800', instagram: 'https://www.instagram.com/albawabamena/', facebook: 'https://www.facebook.com/albawabannews', linkedin: 'https://www.linkedin.com/company/al-bawaba-group', image: 'https://www.albawaba.com/themes/custom/abn/logo-print.png', twitter: 'https://twitter.com/AlBawaba', da: 72, dr: 78 },
    { sn: 29, region: 'Middle East', publication_name: 'Middle East Construction News', publication_url: 'https://meconstructionnews.com/', language: 'English', publication_primary_focus: 'Real Estate', practical_tat: '5', price_usd: '2,000', instagram: 'https://www.instagram.com/meconstructionnews/', facebook: 'https://www.facebook.com/meconstructionnews', linkedin: 'https://www.linkedin.com/company/middle-east-construction-news/', image: 'https://meconstructionnews.com/wp-content/themes/mecn-theme/images/logo.png', twitter: 'https://twitter.com/mecn_tweets', da: 46, dr: 49 },
    { sn: 30, region: 'Middle East', publication_name: 'Tech it UP Middle East', publication_url: 'https://techitupme.com/', language: 'English', publication_primary_focus: 'Tech', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/techitupme/', facebook: 'https://www.facebook.com/techitupme', linkedin: 'https://www.linkedin.com/company/techitup-middle-east/', image: 'https://i0.wp.com/techitupme.com/wp-content/uploads/2017/11/cropped-cropped-logo-1.png?fit=1179%2C288&ssl=1', twitter: 'https://twitter.com/Techitupme', da: 33, dr: 45 },
    { sn: 31, region: 'Middle East', publication_name: 'Intelligent CIO Middle East', publication_url: 'https://www.intelligentcio.com/me/', language: 'English', publication_primary_focus: 'Tech', practical_tat: '30', price_usd: '2,500', instagram: '', facebook: '', linkedin: '', image: '', twitter: '', da: 34, dr: null },
    { sn: 32, region: 'Middle East', publication_name: 'Tahawultech', publication_url: 'https://www.tahawultech.com/', language: 'English', publication_primary_focus: 'Tech', practical_tat: '10', price_usd: '3,000', instagram: '', facebook: '', linkedin: '', image: 'https://www.tahawultech.com/wp-content/uploads/2018/06/tahawultech_com-339x81.png', twitter: 'https://twitter.com/tahawultech', da: 31, dr: null },
    { sn: 33, region: 'Middle East', publication_name: 'Arabian Business (Standard)', publication_url: 'https://www.arabianbusiness.com/', language: 'English / Arabic', publication_primary_focus: 'Magazine', practical_tat: '15', price_usd: '2,000', instagram: '', facebook: 'http://www.facebook.com/share.php?u=https://www.arabianbusiness.com/', linkedin: 'https://news.google.com/publications/CAAqBwgKMMOIoAkw5uxv?ceid=US:en&oc=3&hl=en-US&gl=US', image: '', twitter: 'http://twitter.com/share?text=Homepage&url=https://www.arabianbusiness.com/', da: 86, dr: 84 },
    { sn: 34, region: 'Middle East', publication_name: 'Arabian Business (Premium)', publication_url: 'https://www.arabianbusiness.com/', language: 'English / Arabic', publication_primary_focus: 'Magazine', practical_tat: '15', price_usd: '14,000', instagram: '', facebook: 'http://www.facebook.com/share.php?u=https://www.arabianbusiness.com/', linkedin: 'https://news.google.com/publications/CAAqBwgKMMOIoAkw5uxv?ceid=US:en&oc=3&hl=en-US&gl=US', image: '', twitter: 'http://twitter.com/share?text=Homepage&url=https://www.arabianbusiness.com/', da: 86, dr: 84 },
    { sn: 35, region: 'Middle East', publication_name: 'Forbes Middle East', publication_url: 'https://www.forbesmiddleeast.com/', language: 'English / Arabic', publication_primary_focus: 'Magazine', practical_tat: '20', price_usd: '24,000', instagram: 'https://www.instagram.com/ForbesMiddleEast/', facebook: 'https://www.facebook.com/forbes.ME', linkedin: 'https://www.linkedin.com/company/forbes-middle-east---arab-publisher-house/', image: 'https://www.forbesmiddleeast.com/images/c02ede95b40bd516dabe7102eaa27d51-logo-white.svg', twitter: 'https://twitter.com/forbesme', da: 72, dr: 84 },
    { sn: 36, region: 'Middle East', publication_name: 'CEO Middle East', publication_url: 'https://www.ceo-middleeast.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '5,000', instagram: 'https://www.instagram.com/ceomiddleeast/', facebook: 'https://www.facebook.com/CEOMiddleEast/', linkedin: 'https://www.linkedin.com/company/ceo-middle-east/', image: 'https://www.ceo-middleeast.com/wp-content/themes/itp-ceo-v2/assets/images/logo.svg', twitter: 'https://twitter.com/CEOMiddleEast', da: 38, dr: 38 },
    { sn: 37, region: 'Middle East', publication_name: 'Enterpreneur Middle East (Standard)', publication_url: 'https://www.entrepreneur.com/en-ae', language: 'English / Arabic', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '2,000', instagram: 'https://www.instagram.com/EntMagazineME', facebook: 'https://www.facebook.com/EntMagazineme', linkedin: 'https://www.linkedin.com/company/entrepreneur-me', image: 'https://assets.entrepreneur.com/static/20250528071605-Ent-ME-Logo-Black-1.svg', twitter: 'https://x.com/entmagazineme', da: 66, dr: null },
    { sn: 38, region: 'Middle East', publication_name: 'Enterpreneur Middle East (Premium)', publication_url: 'https://www.entrepreneur.com/en-ae', language: 'English / Arabic', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '8,000', instagram: 'https://www.instagram.com/EntMagazineME', facebook: 'https://www.facebook.com/EntMagazineme', linkedin: 'https://www.linkedin.com/company/entrepreneur-me', image: 'https://assets.entrepreneur.com/static/20250528071605-Ent-ME-Logo-Black-1.svg', twitter: 'https://x.com/entmagazineme', da: null, dr: null },
    { sn: 39, region: 'Middle East', publication_name: 'Economy Middle East', publication_url: 'https://economymiddleeast.com/', language: 'English / Arabic', publication_primary_focus: 'Magazine', practical_tat: '15', price_usd: '12,000', instagram: 'https://www.instagram.com/economymiddleeast/', facebook: 'https://www.facebook.com/economymiddleeast', linkedin: 'https://www.linkedin.com/company/economymiddleeast/', image: 'https://economymiddleeast.com/wp-content/themes/bricks-child/assets/images/logo-dark.svg', twitter: 'https://twitter.com/economymiddleea', da: 52, dr: 59 },
    { sn: 40, region: 'Middle East', publication_name: 'Business Today Middle East', publication_url: 'https://www.businesstoday.me/', language: 'English', publication_primary_focus: 'General', practical_tat: '10', price_usd: '5,000', instagram: 'https://www.instagram.com/biztodayme/', facebook: 'https://www.facebook.com/biztodayme/', linkedin: 'https://www.linkedin.com/company/business-today-middle-east/', image: 'https://www.businesstoday.me/wp-content/uploads/2023/01/BusinessToday_logo-red-1.png', twitter: 'https://x.com/biztodayme', da: 33, dr: 36 },
    { sn: 41, region: 'Middle East', publication_name: 'Finance Middle East', publication_url: 'https://www.financemiddleeast.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '6,000', instagram: 'https://www.instagram.com/financemeast/', facebook: 'https://www.facebook.com/FinanceMEast', linkedin: 'https://www.linkedin.com/company/financemeast/', image: 'https://www.financemiddleeast.com/cloud/2023/12/fme-logo-1.svg', twitter: 'https://twitter.com/FinanceMEast', da: 38, dr: 45 },
    { sn: 42, region: 'Middle East', publication_name: 'Law Middle East', publication_url: 'https://www.law-middleeast.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '6,000', instagram: 'https://www.instagram.com/lawmiddleeast/', facebook: 'https://www.facebook.com/lawmiddleeast', linkedin: 'https://www.linkedin.com/company/lawmiddleeast/', image: 'https://www.law-middleeast.com/cloud/2023/10/Law-Middle-East-logo-white-long.svg', twitter: 'https://twitter.com/lawmiddleeast', da: 25, dr: 30 },
    { sn: 43, region: 'Middle East', publication_name: 'Facilities Management Middle East', publication_url: 'https://www.fm-middleeast.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '6,000', instagram: 'https://www.instagram.com/fm_middleeast/', facebook: 'https://www.facebook.com/FMMiddleEast/', linkedin: 'https://www.linkedin.com/showcase/fm-middle-east/', image: 'https://www.fm-middleeast.com/cloud/2025/08/26/FM_Logo_Vertical_Black-1.png', twitter: 'https://x.com/FMMiddleEast', da: 30, dr: null },
    { sn: 44, region: 'Middle East', publication_name: 'Logistics Middle East', publication_url: 'https://www.logisticsmiddleeast.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '6,000', instagram: 'https://www.instagram.com/logisticsmiddleeast/', facebook: 'https://www.facebook.com/LogisticsMiddleEast/', linkedin: 'https://www.linkedin.com/showcase/logistics-middle-east/', image: 'https://www.logisticsmiddleeast.com/cloud/2023/06/15/logo_black-1.png', twitter: 'https://x.com/logisticsme', da: 52, dr: 48 },
    { sn: 45, region: 'Middle East', publication_name: 'Construction Business News Middle East', publication_url: 'https://www.cbnme.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '4,000', instagram: 'https://www.instagram.com/_cbnme/', facebook: 'https://www.facebook.com/cbnme', linkedin: 'https://linkedin.com/showcase/13270275/', image: 'https://www.cbnme.com/wp-content/uploads/2025/12/cbnme-logo-1.png', twitter: 'https://twitter.com/CBN_ME', da: 35, dr: null },
    { sn: 46, region: 'Middle East', publication_name: 'Construction Week News Online', publication_url: 'https://www.constructionweekonline.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '4,000', instagram: 'https://www.instagram.com/constructionweek/', facebook: 'https://www.facebook.com/ConstructionWeekOnline', linkedin: 'https://www.linkedin.com/company/constructionweekonline/', image: 'https://www.constructionweekonline.com/cloud/2021/04/01/CW-Logo.png', twitter: 'https://twitter.com/constructionwk', da: 52, dr: 68 },
    { sn: 47, region: 'Middle East', publication_name: 'Design Middle East', publication_url: 'https://design-middleeast.com/', language: 'English', publication_primary_focus: 'Magazine', practical_tat: '10', price_usd: '5,000', instagram: '', facebook: '', linkedin: '', image: '', twitter: '', da: 28, dr: null },
    { sn: 48, region: 'Middle East', publication_name: 'CNN Business Arabic', publication_url: 'https://cnnbusinessarabic.com/', language: 'Arabic', publication_primary_focus: 'News', practical_tat: '25', price_usd: '30,000', instagram: '', facebook: '', linkedin: '', image: 'https://logo.page-source.com/resizeimage.ashx?ig=cnnbusinessarabic.com&sz=284403', twitter: '', da: 46, dr: null },
    { sn: 49, region: 'Kuwait', publication_name: 'Arab Times Online', publication_url: 'https://www.arabtimesonline.com/', language: 'English', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/arabtimeskuwait/', facebook: 'https://www.facebook.com/arabtimeskuwait/', linkedin: 'https://www.linkedin.com/company/arab-times-kuwait', image: 'https://www.arabtimesonline.com/theme_arabtimes/images/theme-logo.svg', twitter: 'https://twitter.com/arabtimeskuwait', da: 52, dr: 61 },
    { sn: 50, region: 'Kuwait', publication_name: 'Kuwait Times', publication_url: 'https://kuwaittimes.com/', language: 'English', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '1,500', instagram: 'https://www.instagram.com/kuwaittimes', facebook: 'https://www.facebook.com/kuwaittimes', linkedin: 'https://www.linkedin.com/company/kuwait-times', image: 'https://kuwaittimes.com/theme_kuwaittimes/images/logo.svg', twitter: 'https://twitter.com/kuwaittimes', da: 57, dr: 61 },
    { sn: 51, region: 'Global', publication_name: 'Al Jazeera', publication_url: 'https://www.Aljazeera.com', language: 'English', publication_primary_focus: 'News Channel', practical_tat: '15', price_usd: '16,000', instagram: 'https://www.instagram.com/aljazeera', facebook: 'https://www.facebook.com/aljazeera', linkedin: 'https://www.linkedin.com/company/al-jazeera-media-network', image: 'https://www.aljazeera.com/static/media/aljazeera-logo.png', twitter: 'https://twitter.com/ajenglish', da: 94, dr: 91 },
    { sn: 52, region: 'Bahrain', publication_name: 'Trade Arabia', publication_url: 'https://www.tradearabia.com/', language: 'English', publication_primary_focus: 'Business, Trade, Economy, Finance, General', practical_tat: '5', price_usd: '1,000', instagram: '', facebook: '', linkedin: '', image: 'https://www.tradearabia.com/Content/imgs/logoTA.webp', twitter: '', da: 35, dr: null },
    { sn: 53, region: 'Bahrain', publication_name: 'Gulf Digital News / GDN Online', publication_url: 'https://www.gdnonline.com/index.html', language: 'English', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/gdnonline/', facebook: 'https://www.facebook.com/gdnonline', linkedin: 'https://www.linkedin.com/company/gdn-online', image: 'https://www.gdnonline.com/content/images/gulfdailynewslogo.png?v=1.1', twitter: 'https://twitter.com/gdnonline', da: 52, dr: 61 },
    { sn: 54, region: 'Bahrain', publication_name: 'The Daily Tribune / News of Bahrain', publication_url: 'https://www.newsofbahrain.com/', language: 'English', publication_primary_focus: 'Newspaper', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/newsofbahrain/', facebook: 'https://www.facebook.com/newsofbahrain/', linkedin: 'https://www.linkedin.com/company/daily-tribune-news-of-bahrain/', image: 'https://www.newsofbahrain.com/images/logo.png', twitter: 'https://twitter.com/newsofbahrain', da: 52, dr: 48 },
    { sn: 55, region: 'Bahrain', publication_name: 'Gulf Construction Online', publication_url: 'https://gulfconstructiononline.com/', language: 'English', publication_primary_focus: 'Real Estate and Construction', practical_tat: '5', price_usd: '1,000', instagram: 'https://www.instagram.com/gulfconstructionmagazine/', facebook: 'https://web.facebook.com/GulfConstructionOnline/?_rdc=1&_rdr', linkedin: 'https://www.linkedin.com/showcase/gulf-construction-magazine/', image: 'https://gulfconstructiononline.com/Content/img/gclogo_1.png', twitter: 'https://twitter.com/Gulf_const', da: 26, dr: null },
    { sn: 56, region: 'Bahrain', publication_name: 'Gulf Industry Online', publication_url: 'https://gulfindustryonline.com/', language: 'English', publication_primary_focus: 'Manufacturing', practical_tat: '5', price_usd: '1,000', instagram: '', facebook: '', linkedin: '', image: 'https://gulfindustryonline.com/Content/images/gulfindustrylogo.png', twitter: '', da: 20, dr: null }
];

async function findOrCreateGroup(groupName) {
    if (!groupName) return null;
    try {
        const sql = 'SELECT * FROM groups WHERE group_name = $1';
        const result = await db.query(sql, [groupName]);
        if (result.rows[0]) return result.rows[0].id;

        const groupData = {
            group_name: groupName,
            group_location: 'Global',
            status: 'approved',
            is_active: true
        };
        const savedGroup = await Group.create(groupData);
        return savedGroup.id;
    } catch (error) {
        console.error(`Error with group ${groupName}:`, error.message);
        return null;
    }
}

async function populateMarketplace() {
    try {
        console.log('Starting marketplace population...');

        // Wipe existing publications first
        console.log('Deleting all existing publications...');
        await db.query('TRUNCATE publications RESTART IDENTITY CASCADE');
        console.log('Existing publications deleted.');

        let successCount = 0;
        let errorCount = 0;

        for (const pub of PUBLICATIONS_DATA) {
            try {
                const price = pub.price_usd ? parseFloat(pub.price_usd.replace(/,/g, '')) : 0;
                const da = pub.da ? parseInt(pub.da) : 0;
                const dr = pub.dr ? parseInt(pub.dr) : 0;
                const tat = pub.practical_tat ? parseInt(pub.practical_tat) : 0;

                const groupId = await findOrCreateGroup(`${pub.region} Publications`);

                const socials = [pub.instagram, pub.facebook, pub.linkedin, pub.twitter].filter(url => !!url).join(',');

                const data = {
                    group_id: groupId,
                    publication_sn: `PUB-${pub.sn.toString().padStart(3, '0')}`,
                    publication_grade: 'A',
                    publication_name: pub.publication_name,
                    publication_website: pub.publication_url,
                    publication_price: price,
                    agreement_tat: tat,
                    practical_tat: tat,
                    publication_socials_icons: socials,
                    publication_language: pub.language,
                    publication_region: pub.region,
                    publication_primary_industry: pub.publication_primary_focus,
                    da: da,
                    dr: dr,
                    words_limit: 500,
                    number_of_images: 2,
                    do_follow_link: true,
                    live_on_platform: true,
                    status: 'approved'
                };

                await Publication.create(data);
                successCount++;
                console.log(`Saved Marketplace [${pub.sn}]: ${pub.publication_name}`);
            } catch (err) {
                console.error(`Error saving ${pub.publication_name}:`, err.message);
                errorCount++;
            }
        }

        console.log(`Marketplace population finished. Success: ${successCount}, Errors: ${errorCount}`);
        process.exit(0);
    } catch (err) {
        console.error('Fatal error during marketplace population:', err);
        process.exit(1);
    }
}

populateMarketplace();
